name: amlive
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_feather_icons: ^1.0.3
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  sliding_up_panel:
    git:
      url: git://github.com/n-keist/sliding_up_panel.git

flutter:
  uses-material-design: true
  assets:
    - assets/icons/heart-black.svg
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
